[[redirects]]
  from = "/*"
  to = "https://thingproxy.freeboard.io/fetch/"

[[headers]]
  for = "/*"
  [header.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"